config/routes.rb
Rails.application.routes.draw do
  resources :projects
  devise_for :users
  resources :skills
  root 'pages#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :is_admin?
    
    private
    def is_admin?
        if current_user.admin?
        else
            puts "You are not an admin"
        end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @skills = Skill.all
    @projects = Project.all
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: %i[ show edit update destroy ]
  before_action :is_admin?

  # GET /projects or /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1 or /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects or /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: "Project was successfully created." }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1 or /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: "Project was successfully updated." }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1 or /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: "Project was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :date, :description, :image)
    end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: %i[ show edit update destroy ]
  before_action :is_admin?

  # GET /skills or /skills.json
  def index
    @skills = Skill.all
  end

  # GET /skills/1 or /skills/1.json
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills or /skills.json
  def create
    @skill = Skill.new(skill_params)

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: "Skill was successfully created." }
        format.json { render :show, status: :created, location: @skill }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /skills/1 or /skills/1.json
  def update
    respond_to do |format|
      if @skill.update(skill_params)
        format.html { redirect_to @skill, notice: "Skill was successfully updated." }
        format.json { render :show, status: :ok, location: @skill }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1 or /skills/1.json
  def destroy
    @skill.destroy
    respond_to do |format|
      format.html { redirect_to skills_url, notice: "Skill was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_skill
      @skill = Skill.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def skill_params
      params.require(:skill).permit(:name, :description, :icon)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/layouts/_bloggrid.html.erb
        <section class="page-section bg-light" id="portfolio">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">BLOGS</h2>
                    <h3 class="section-subheading text-muted">Stay with codes :=></h3>
                </div>
                <div class="row">
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Portfolio item 1-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal1">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                <img class="img-fluid" src="/start/assets/img/portfolio/9.jpeg" alt="..." />
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">My Journey From 0 to 1</div>
                                <div class="portfolio-caption-subheading text-muted">11/15/2021</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Portfolio item 2-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal2">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                <img class="img-fluid" src="/start/assets/img/portfolio/10.png" alt="..." />
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">Using localStorage to #{Persist} with React!</div>
                                <div class="portfolio-caption-subheading text-muted">10/22/2021</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6 mb-4">
                        <!-- Portfolio item 3-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal3">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                <img class="img-fluid" src="/start/assets/img/portfolio/11.jpeg" alt="..." />
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">VS Code Extensions That Will Make You Code Faster! – 2021</div>
                                <div class="portfolio-caption-subheading text-muted">10/12/2021</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6 mb-4 mb-lg-0">
                        <!-- Portfolio item 4-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal4">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                <img class="img-fluid" src="/start/assets/img/portfolio/8.png" alt="..." />
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">How I Created My First React Project</div>
                                <div class="portfolio-caption-subheading text-muted">10/01/2021</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6 mb-4 mb-sm-0">
                        <!-- Portfolio item 5-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal5">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                <img class="img-fluid" src="/start/assets/img/portfolio/7.png" alt="..." />
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">What is Arrow Functions? Part 1</div>
                                <div class="portfolio-caption-subheading text-muted">09/13/2021</div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 col-sm-6">
                        <!-- Portfolio item 6-->
                        <div class="portfolio-item">
                            <a class="portfolio-link" data-bs-toggle="modal" href="#portfolioModal6">
                                <div class="portfolio-hover">
                                    <div class="portfolio-hover-content"><i class="fas fa-plus fa-3x"></i></div>
                                </div>
                                <img class="img-fluid" src="/start/assets/img/portfolio/6.jpeg" alt="..." />
                            </a>
                            <div class="portfolio-caption">
                                <div class="portfolio-caption-heading">My dream job: Coding!</div>
                                <div class="portfolio-caption-subheading text-muted">08/03/2021</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>

app/views/layouts/_footer.html.erb
        <footer class="footer py-4">
            <div class="container">
                <div class="row align-items-center">
                    <div class="col-lg-4 text-lg-start">Copyright &copy; <%= Date.today.year %></div>
                    <div class="col-lg-4 my-3 my-lg-0">
                        
                        <a class="btn btn-dark btn-social mx-2" href="https://www.linkedin.com/in/kurucaner/"><i class="fab fa-linkedin-in"></i></a>
                    </div>
                    <div class="col-lg-4 text-lg-end">
                        <a class="link-dark text-decoration-none me-3" href="#!">Privacy Policy</a>
                        <a class="link-dark text-decoration-none" href="#!">Terms of Use</a>
                    </div>
                </div>
            </div>
        </footer>

app/views/layouts/_navbar.html.erb
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand js-scroll-trigger" href="#page-top">CK.</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars ms-1"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav text-uppercase ms-auto py-4 py-lg-0">
                        <li class="nav-item"><a class="nav-link" href="#services">SKILLS</a></li>
                        <li class="nav-item"><a class="nav-link" href="#portfolio">STUFF I'VE WRITTEN</a></li>
                        <li class="nav-item"><a class="nav-link" href="#about">STUFF I'VE BUILT</a></li>
                        <li class="nav-item"><a class="nav-link" href="#contact">Contact</a></li>
                    </ul>
                </div>
            </div>
        </nav>

app/views/layouts/_post6.html.erb
<div class="portfolio-modal modal fade" id="portfolioModal6" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="close-modal" data-bs-dismiss="modal"><img src="/start/assets/img/close-icon.svg" alt="Close modal" /></div>
                    <div class="container">
                        <div class="row justify-content-center">
                            <div class="col-lg-8">
                                <div class="modal-body">
                                    <!-- Project details-->
                                    <h2 class="text-uppercase">My dream job: Coding!</h2>
                                    <p class="item-intro text-muted">by Caner Kuru</p>
                                    <img class="img-fluid d-block mx-auto" src="/start/assets/img/portfolio/6.jpeg" alt="..." />
                                    <p>Hello, <br />Universe!
It’s my first ever blog post, and I want to tell you why I chose Software Engineering as a profession.
I had my first PC when I was nine years old, and I broke my system five times in two weeks by deleting a bunch of system32 files. I have no idea why but I was always so into coding, hacking, designing more than playing video games, and I never lost that passion. I self-learned HTML and created many websites for myself and my friends.
At the time, I was playing the online video game called Knight Online, and I hated all the GMs and all the bugs and glitches. So I created my first private Knight Online game server and kept it open for more than two years for players. I coded a flawed security system for cheaters, designed a game panel, and fixed many bugs that the original game company did not improve for years.
Then I chose finance as my future profession, and I now realize it was the wrong path. I started studying software engineering almost a month ago, and it’s one of the hardest things I’ve ever faced in my life, but I love it. I think about coding/codes doesn’t matter what I do or where I’m at. I even dream about it. Yep, I completely lost it, but what can I do? It gives me butterflies, and I feel like I finally found the one for me. I’m already in love with it.
I’ll keep learning and keep updating myself at coding. I’ll try my best to become an incredible coder one day. Now it’s time to get back coding.
Ciao everyone!</p>
                                    <ul class="list-inline">
                                        <li>
                                            
                                            4 min read
                                        </li>
                                        <li>
                                            
                                            08/03/2021
                                        </li>
                                    </ul>
                                    <button class="btn btn-primary btn-xl text-uppercase" data-bs-dismiss="modal" type="button">
                                        <i class="fas fa-times me-1"></i>
                                        Close Blog
                                    </button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>

app/views/layouts/_projects.html.erb
        <section class="page-section" id="about">
            <div class="container">
                <div class="text-center">
                    <h2 class="section-heading text-uppercase">STUFF I'VE BUILT</h2>
                    <h3 class="section-subheading text-muted">Project links will go online 5 seconds after your click!</h3>
                </div>
                <ul class="timeline">
                    <li>
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="/start/assets/img/about/1.jpg" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>November 2021</h4>
                                <h4 class="subheading">Pixmarkt</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Phase 5 — Graduation Project. I’ve combined everything, and I learned since day one, and I learned so many new things in this project like AWS and devise gem. Instagram inspired me for this project.<br /><a href="https://pixmarkt.herokuapp.com/">Pixmarkt</a></p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="/start/assets/img/about/1.jpg" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>October 2021</h4>
                                <h4 class="subheading">Beeper</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">Chat Iron, Beeper, and following and my final project are different despite one forerunner of the other. Twitter inspired me for this project, and my project partner and I did an excellent job in 5 days.<br /><a href="https://beeperapp.herokuapp.com/">Beeper</a></p></div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="/start/assets/img/about/1.jpg" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>September 2021</h4>
                                <h4 class="subheading">Chat Iron</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">I’ll never forget this project. London and I wanted to create something unique and fun. When I told her about creating a chat app, we both were so excited. We knew it would be challenging, but it was so much worse than what we were expecting. We didn’t have rails resources; therefore, we had to code authorization and authentication from scratches. We had nightmares and sleepless nights. We forgot to eat! No exaggeration at all! But we made it 5 minutes before the presentation.<br />No online example!</p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="/start/assets/img/about/1.jpg" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>September 2021</h4>
                                <h4 class="subheading">Madflix</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">This was my solo project at the end of Phase 2. React got into my life at this point. It is a fantastic framework or library. Whichever you want to call it. :) IMDB and Madflix inspired me for this project. I’ve wanted to have a movie website since I was very little and I finally achieved my dream.<br /><a href="https://kurucaner.github.io/madflix/">Madflix</a></p></div>
                        </div>
                    </li>
                    <li>
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="/start/assets/img/about/1.jpg" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>August 2021</h4>
                                <h4 class="subheading">Cackle Card</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">My project partner and I finished this app at the end of Phase 1. I’ve learned so much about functions and fetching data in JS. It was challenging but entertaining at the same time.<br /><a href="https://kurucaner.github.io/apiproject/">Cackle Card</a></p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image"><img class="rounded-circle img-fluid" src="/start/assets/img/about/1.jpg" alt="..." /></div>
                        <div class="timeline-panel">
                            <div class="timeline-heading">
                                <h4>July 2021</h4>
                                <h4 class="subheading">Exploring Istanbul</h4>
                            </div>
                            <div class="timeline-body"><p class="text-muted">I was born and raised in Turkey, and I wanted my first project to be about my hometown. It’s an elementary single web page, but this is the project when I learned how vital building structure is.<br /><a href="https://kurucaner.github.io/example-repository/">Exploring Istanbul</a></p></div>
                        </div>
                    </li>
                    <li class="timeline-inverted">
                        <div class="timeline-image">
                            <h4>
                                MORE
                                <br />
                                IS
                                <br />
                                COOKING!
                            </h4>
                        </div>
                    </li>
                </ul>
            </div>
        </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Caner's Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

            <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="/start/css/styles.css" rel="stylesheet" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  </head>

  <body id="page-top">
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with(model: project) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
        <% project.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :date %>
    <%= form.text_field :date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image %>
  </div>

    <div class="field">
    <%= form.label :link %>
    <%= form.text_field :link %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">NAME</th>
      <th scope="col">DATE</th>
      <th scope="col">DESCRIPTION</th>
      <th scope="col">IMAGE</th>
      <th scope="col">LINK</th>
    </tr>
  </thead>
  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <th scope="row"><%= project.id %></th>
        <td><%= project.name %></td>
        <td><%= project.date %></td>
        <td><%= project.description %></td>
        <td><%= project.image %></td>
        <td><%= project.link %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @project.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Image:</strong>
  <%= @project.image %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/skills/_form.html.erb
<div class="container">
<%= form_with(model: skill) do |form| %>
  <% if skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
        <% skill.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :name %>
    <%= form.text_field :name, :class => 'form-control' %>
  </div>

  <div class="mb-3">
    <%= form.label :descriptiong %>
    <%= form.text_area :description, :class => 'form-control'%>
  </div>

  <div class="mb-3">
    <%= form.label :icon %>
    <%= form.text_field :icon, :class => 'form-control' %>
  </div>

  <div class="d-grid gap-2 d-md-block">
    <%= form.submit :class => 'btn btn-primary' %>
  </div>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h1>Skills</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">NAME</th>
      <th scope="col">DESCRIPTION</th>
      <th scope="col">ICON</th>
    </tr>
  </thead>
  <tbody>
    <% @skills.each do |skill| %>
      <tr>
        <th scope="row"><%= skill.id %></th>
        <td><%= skill.name %></td>
        <td><%= skill.description %></td>
        <td><%= skill.icon %></td>
        <td><%= link_to 'Show', skill %></td>
        <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
        <td><%= link_to 'Destroy', skill, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New Skill</h1>

<%= render 'form', skill: @skill %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @skill.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @skill.description %>
</p>

<p>
  <strong>Icon:</strong>
  <%= @skill.icon %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>